server:
  port: 8083

#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: 52.201.218.52:9092 // 컨슈머 서버 주소
#      group-id: chatting
#    producer:
#      bootstrap-servers: 52.201.218.52:9092 // 프로듀서 서버 주소


#logging:
#  level:
#    com.example.listener.KafkaConsumer: debug
#    root: debug
